# https://taskfile.dev

version: '3'

env:
  GREETING: Hello, World!
  HOME: "hello"

tasks:
  update-language-tool:
    cmds:
      - curl https://languagetool.org/download/LanguageTool-stable.zip -o embedded-language-tool/LanguageTool-stable.zip
  build:
    cmds:
      - cargo build
  hx:
    deps:
      - build
    cmds:
      - rm -f home/.cache/helix/helix.log
      - env HOME="./home" hx -vvv -w . test-files
  helix:
    deps:
      - build
    cmds:
      - rm -f home/.cache/helix/helix.log
      - env HOME="./home" helix -vvv -w . test-files
      
